build:
  image: drone/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - AWS_ACCESS_KEY_ID=AKID1234567890
    - AWS_SECRET_ACCESS_KEY=MY-SECRET-KEY
  commands:
    - |
    git submodule init
    git submodule update
    sudo apt-get install -y -qq python-pip python-virtualenv libevent-dev
    go get github.com/aws/aws-sdk-go/...
    go get github.com/boltdb/bolt
    go get github.com/gorilla/mux
    go get gopkg.in/mgo.v2/bson
    go build -o cmd/gofakes3 cmd/main.go
    go test -v ./...
    #./s3test/test.sh
