# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11-rc
    working_directory: ~/github.com/tkeech1/gomodules
    steps:
    - checkout
    - run: go test -race
